version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /vendor/github.com/vmihailenco/msgpack/v5
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /vendor/go.opentelemetry.io/otel
    schedule:
      interval: daily
